feat(apm): add apm transactions on requests.
alphawolfteam/friends-user-service pull request #10
Opened 2021-01-17 12:46 UTC by yonatandt

Closes #9
Signed-off-by: YonatanTal <yonatald@gmail.com>

2021-01-24 13:08 UTC, lustigy96 requested changes

2021-01-24 13:08 UTC, lustigy96 commented on src/server.ts
> +import * as http from 'http';
We said that this http is וnnecessary

2021-01-24 13:08 UTC, lustigy96 commented on src/utils/wrappers.ts
> +}
```suggestion
function extractTraceparent(req: Request): string | undefined => {
   req.header(apmConfig.traceParentHeader); // add as config
}
```
This syntax is better for eslint.

2021-01-25 08:21 UTC, yonatandt commented on src/server.ts
> +import * as http from 'http';
`http` is necessary. We should use the standard library of `http` and not one from npm like [this](https://www.npmjs.com/package/http).

2021-01-25 08:26 UTC, yonatandt commented on src/utils/wrappers.ts
> +}
changed the style.

2021-01-26 14:26 UTC, lustigy96 approved these changes

2021-01-26 15:58 UTC, merged